# Generated by Django 4.2.2 on 2023-06-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendariumApp', '0002_remove_cumpleano_id_user_remove_evento_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='priority',
            field=models.CharField(max_length=255),
        ),
    ]
