# Generated by Django 4.2.2 on 2023-06-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendariumApp', '0003_alter_tarea_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='realizado',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
